### ISSUE TITLE
The up-arrow on the expand toggle starts off being invisible/not being there

### ISSUE THREAD

**Issue by JReesW** [hexathe6/kiraton#5]
![image](https://github.com/hexathe6/kiraton/assets/12934721/ebeb4f82-90cb-412e-9bb3-a8d60de2aca9)  
  
As can be seen above, the expand toggles are just empty grey boxes.
Once toggled the down-arrow appears, and if toggled again the up-arrow appears as expected, seen below.  
  
![image](https://github.com/hexathe6/kiraton/assets/12934721/8c46a72b-1b9c-4740-94ed-3599d0984846)  
  
This caused me to initially not realise that they were expand toggles, thus making me miss out on content

**Comment by hexathe6** [comment]
@JReesW this should be fixed in the latest commit (8036740), can you confirm? (there's no scenario that i can imagine would cause the fix to fail, but idk)

**Comment by JReesW** [comment]
can confirm it is fixed for me now!
